### ISSUE TITLE
LDAP authentication fails if username contains "-"

### ISSUE THREAD

**Issue by madmas** [sdelements/lets-chat-ldap#14]
Hi,
we're experiencing a problem with username containing a "-", e.g. for composed names.
From my expression, this is related tothe "-" as all other users are working fine.

here is what lets-chat log to the console:

```
{ [ValidationError: Validation failed]
  message: 'Validation failed',
  name: 'ValidationError',
  errors: 
   { username: 
      { [ValidatorError: Path `username` is invalid (karl-heinz).]
        message: 'Path `username` is invalid (karl-heinz).',
        name: 'ValidatorError',
        path: 'username',
        type: 'regexp',
        value: 'karl-heinz' } } }
```

Any suggestions what I can do about this?

**Comment by hhaidar** [comment]
This is actually an issue with the app itself.

I've pushed up a branch of let's chat that allows `-` in usernames: [fix/username_dash](https://github.com/sdelements/lets-chat/pull/426)

Please try that and I will merge it in master.

**Comment by madmas** [comment]
Hi, sorry for the long delay. I was able to give it a try this morning and got this error:

```
SyntaxError: Invalid regular expression: /^[^\.][a-z0-9_-\.]+[^\.]$/: Range out of order in character class
    at new RegExp (<anonymous>)
    at Object.<anonymous> (/home/admin/letschat/lets-chat/app/models/user.js:70:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/admin/letschat/lets-chat/migrootions/1421183479874-users.js:3:12)
    at Module._compile (module.js:456:26)
```

I changed the regex to 

```
    match: /^[^\.][a-z0-9_\.-]+[^\.]$/i
```

and it works.

So we are able to login even with a - in the username :+1:

**Comment by hhaidar** [comment]
@madmas awesome, something like this has been merged into master
