### ISSUE TITLE
Update documentation to show ENV configurations

### ISSUE THREAD

**Issue by vwbusguy** [sdelements/lets-chat-ldap#23]
Using ENV configurations is especially important for Docker implenetations.  There were also some variables that aren't intuitive based on the current documentation "bindDn vs BIND_DN" etc.  Here's a list of mappings I've found:

LCB_AUTH_PROVIDERS
LCB_AUTH_LDAP_CONNECT_SETTINGS_URL
LCB_AUTH_LDAP_CONNECT_SETTINGS_TLS_OPTIONS_CA
LCB_AUTH_LDAP_BIND_OPTIONS_BIND_DN
LCB_AUTH_LDAP_BIND_OPTIONS_BIND_CREDENTIALS
LCB_AUTH_LDAP_SEARCH_BASE
LCB_AUTH_LDAP_SEARCH_OPTS_FILTER
LCB_AUTH_LDAP_SEARCH_OPTS_SCOPE
LCB_AUTH_LDAP_FIELD_MAPPINGS_UID
LCB_AUTH_LDAP_FIELD_MAPPINGS_USERNAME
LCB_AUTH_LDAP_FIELD_MAPPINGS_EMAIL
LCB_AUTH_LDAP_FIELD_MAPPINGS_FIRSTNAME
LCB_AUTH_LDAP_FIELD_MAPPINGS_LASTNAME
LCB_AUTH_LDAP_FIELD_MAPPINGS_DISPLAY_NAME

Note also that the Search Base and BindDN should *not* be quotation mark wrapped as they are in the yml example.

**Comment by hhaidar** [comment]
Thank you, I've added it to the `README` in e384a5a5dda7acae9e5e8bc99d076575e48a4ad0
