### ISSUE TITLE
OS X Server example

### ISSUE THREAD

**Issue by iamso** [sdelements/lets-chat-ldap#7]
Could you show me an example for the following scenario?

Server: OS X 10.9 Server with Open Directory master
Server ip: 10.0.1.20
Server url: server.example.com
Open Directory Admin: diradmin
Password: dirpass

I can't seem to get it right.

Thanks

**Comment by funkaoshi** [comment]
You might want to reach out to people on Server Fault. We really don't have the experience to help you set up LDAP. The issue tracker is meant to track bugs against the plugin code.
